---
# handlers file for java

- name: validate java
  shell: "java -version 2>&1 | grep {{ java_release }}"
  changed_when: False 

- name: Save Java details
  copy:
    content: >
      {
        "version": "{{java_release}}",
        "build": "{{java_build.stdout}}",
        "path": "{{java_info.dest}}",
        "installed": "{{ ansible_date_time.iso8601 }}"
      }
    dest: /etc/ansible/facts.d/java.fact
  become: yes 


